include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = OriginMotionLockPrefs

OriginMotionLockPrefs_FILES = OMLRootListController.m
OriginMotionLockPrefs_FRAMEWORKS = UIKit
OriginMotionLockPrefs_PRIVATE_FRAMEWORKS = Preferences
OriginMotionLockPrefs_INSTALL_PATH = /Library/PreferenceBundles
OriginMotionLockPrefs_CFLAGS = -fobjc-arc -I$(THEOS)/include
OriginMotionLockPrefs_ARCHS = arm64

include $(THEOS_MAKE_PATH)/bundle.mk
