name: Build Tweak

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld llvm dpkg-dev git make wget libssl-dev unzip curl

      - name: Install ldid manually
        run: |
          sudo wget -qO /usr/local/bin/ldid https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_linux_x86_64
          sudo chmod +x /usr/local/bin/ldid

      - name: Setup Theos and SDK
        run: |
          rm -rf $HOME/theos
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          
          # Cấu hình symlink trỏ đúng công cụ clang/lld để không bị lỗi linker Linux
          mkdir -p $HOME/theos/toolchain/linux/iphone/bin
          ln -sf /usr/bin/clang $HOME/theos/toolchain/linux/iphone/bin/clang
          ln -sf /usr/bin/clang++ $HOME/theos/toolchain/linux/iphone/bin/clang++
          ln -sf /usr/bin/lld $HOME/theos/toolchain/linux/iphone/bin/ld
          
          # Cài bộ iOS SDK chuẩn
          rm -rf $HOME/theos/sdks
          git clone https://github.com/theos/sdks.git $HOME/theos/sdks --depth=1

      - name: Build Package
        env:
          THEOS: /home/runner/theos
        run: |
          make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: packages/*.deb
